# Docker
docker-hub-email: congbang10h@gmail.com
docker-hub-username: congbang10h
docker-hub-password: Bang12345
docker-hub-repo-name: congbang10h/concourse

# Kubernetes
server: <<API SERVER URI>>
namespace: <<NAMESPACE>>
cad: <<CERT AUTH DATA>>
token: <<K8 TOKEN>>